import type {
  ProjectionPrediction,
  ProjectionPredictionSignal,
  ProjectionSample,
} from "../../core/interfaces.ts";
import type { VectorXZ } from "../../../core/math.ts";

/**
 * Minimal obstacle layout shape used by evader-motion projection.
 *
 * The world module owns concrete collision behavior. Projection code only needs
 * enough structure to pass remembered obstacles through that world API.
 */
export type EvaderProjectionObstacleLayout = {
  walls?: Array<{
    id?: string;
    x: number;
    z: number;
    width: number;
    depth: number;
    [key: string]: unknown;
  }>;
  [key: string]: unknown;
};

/**
 * Shared world context for projecting evader positions through future frames.
 */
export type EvaderProjectionWorldContext = {
  columns?: number;
  rows?: number;
  obstacles?: EvaderProjectionObstacleLayout | null;
};

/**
 * Observed and inferred evader motion state used as projection input.
 */
export type EvaderMotionEstimate = {
  position?: VectorXZ | null;
  direction?: VectorXZ | null;
  lastObservedDirection?: VectorXZ | null;
  previousObservedDirection?: VectorXZ | null;
  observedTurnRadiansPerFrame?: number | null;
  observationCount?: number;
  motionObservationCount?: number;
  framesSinceObservation?: number;
  speedEstimateUnitsPerFrame?: number;
};

/**
 * Evidence that the evader tends to turn away from walls.
 */
export type WallAvoidanceEvidence = {
  approachEpisodeCount?: number;
  avoidedApproachCount?: number;
};

/**
 * Pattern module shape needed by projection rectification.
 */
export type PatternProjectionUnit = {
  id?: string;
  predictions?: Array<Record<string, any>>;
};

/**
 * Pattern projection modules keyed by pattern id.
 */
export type PatternProjectionUnitMap = Record<string, PatternProjectionUnit | null | undefined>;

/**
 * Context consumed by the evader-motion direction predictor.
 */
export type EvaderMotionPredictionContext = EvaderProjectionWorldContext & {
  wallAvoidanceEvidence?: WallAvoidanceEvidence | null;
  coupling?: number;
  iterations?: number;
  threshold?: number;
};

/**
 * Direction prediction generated by one evader-motion projection method.
 */
export type EvaderMotionPrediction = ProjectionPrediction & {
  oscillators?: Array<Record<string, unknown>>;
  wallAvoidance?: ProjectionPredictionSignal | null;
  actionable?: boolean;
};

/**
 * Function shape for pluggable frame-to-frame motion predictors.
 */
export type EvaderMotionPredictor = (
  estimate: EvaderMotionEstimate,
  options?: EvaderMotionPredictionContext,
) => EvaderMotionPrediction;

/**
 * Pattern-level projection sample before multiple pattern predictors are
 * rectified into one projection path.
 */
export type EvaderPatternProjectionSample = ProjectionSample & {
  index: number;
  frameOffset: number;
  position: VectorXZ;
  sourcePatternId: string;
  confidence: number;
};

/**
 * One future sample after pattern projections have been combined.
 */
export type RectifiedProjectionFrame = ProjectionSample & {
  index?: number;
  frameOffset: number;
  position: VectorXZ;
  direction: VectorXZ;
  confidence: number;
  confidenceParts: Record<string, unknown>;
  prediction: ProjectionPrediction;
  sourcePatternIds: string[];
  sourcePredictions: Array<Record<string, unknown>>;
};

/**
 * Projection sample persisted across frames for temporary out-of-sight pursuit.
 */
export type PersistedEvaderProjectionSample = {
  dueFrame: number;
  position: VectorXZ | null;
  direction: VectorXZ | null;
  confidence: number;
  sourcePatternIds: string[];
};

/**
 * Mutable state owned by the evader-motion projection module.
 */
export type EvaderMotionProjectionState = {
  elapsedFrames: number;
  lastValidationErrorDistance: number;
  pendingValidations: Array<{
    dueFrame: number;
    position: VectorXZ;
  }>;
  lastActionablePlan: {
    prediction: ProjectionPrediction;
    path: PersistedEvaderProjectionSample[];
    sampleCount: number;
    sampleSpacingFrames: number;
    horizonFrames: number;
  } | null;
  lastActionableFrame: number | null;
};

/**
 * Input to the evader-motion projection planner.
 */
export type EvaderMotionProjectionPlanOptions = {
  estimate?: EvaderMotionEstimate | null;
  patternUnits?: PatternProjectionUnitMap | null;
  evaderVisible?: boolean;
  projectionState?: EvaderMotionProjectionState | null;
  columns?: number;
  rows?: number;
  obstacles?: EvaderProjectionWorldContext["obstacles"];
  horizonFrames?: number;
  sampleSpacingFrames?: number;
};
