from __future__ import annotations

import hashlib
import re
import unittest
from pathlib import Path

from docs.milestones.workflow import (
    apply_handoff,
    parse_table,
    validate_plan_path,
    validate_plan_text,
    validate_repair_cycle_governance_body,
)
from tests.docs.milestone_workflow_fixtures import (
    NEXT_FRONTIER,
    handoff_receipt,
    implementation_review_plan_text,
    ready_plan_text,
)


ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"
MILESTONES = DOCS / "milestones"
CONTRACT_SOURCE = MILESTONES / "README.md"
CONTRACT_RENDER = MILESTONES / "planning-contract.html"
GUIDE = DOCS / "README.md"
ROOT_README = ROOT / "README.md"
STALE_MILESTONE_STATUS = re.compile(
    r"(?im)is the (active|queued) .+ milestone"
)
PR_TEMPLATE = ROOT / ".github" / "pull_request_template.md"
PROPOSAL_PR_TEMPLATE = (
    ROOT / ".github" / "PULL_REQUEST_TEMPLATE" / "proposal.md"
)
PROPOSAL_GUIDANCE = DOCS / "guidance" / "proposal-vs-implementation.md"
PROPOSAL_AMENDMENT_PR_TEMPLATE = (
    ROOT / ".github" / "PULL_REQUEST_TEMPLATE" / "proposal-amendment.md"
)
IMPLEMENTATION_ADJUNCT_PR_TEMPLATE = (
    ROOT / ".github" / "PULL_REQUEST_TEMPLATE" / "implementation-adjunct.md"
)
MILESTONE_PR_TEMPLATE = ROOT / ".github" / "PULL_REQUEST_TEMPLATE" / "milestone.md"
REPAIR_PR_TEMPLATE = ROOT / ".github" / "PULL_REQUEST_TEMPLATE" / "repair.md"
TEST_WORKFLOW = ROOT / ".github" / "workflows" / "tests.yml"


def _plan_header_status(plan_md: Path) -> str:
    match = re.search(
        r"^\| Status \| ([^|]+) \|",
        plan_md.read_text(encoding="utf-8"),
        re.MULTILINE,
    )
    if match is None:
        return ""
    return match.group(1).strip().strip("`")


def _active_plan_paths() -> tuple[Path, Path] | None:
    active: list[tuple[Path, Path]] = []
    for plan_md in sorted(MILESTONES.glob("*/plan.md")):
        if _plan_header_status(plan_md).casefold().startswith("active"):
            active.append((plan_md, plan_md.with_suffix(".html")))
    if len(active) > 1:
        names = ", ".join(str(path.relative_to(ROOT)) for path, _ in active)
        raise AssertionError(f"multiple active milestone plans: {names}")
    if not active:
        return None
    return active[0]


class MilestonePlanningTests(unittest.TestCase):
    def test_rendered_contract_identifies_current_markdown_source(self) -> None:
        source = CONTRACT_SOURCE.read_text(encoding="utf-8")
        rendered = CONTRACT_RENDER.read_text(encoding="utf-8")
        expected_digest = hashlib.sha256(source.encode("utf-8")).hexdigest()
        match = re.search(
            r'<meta name="source-sha256" content="([a-f0-9]{64})">',
            rendered,
        )
        self.assertIsNotNone(match)
        assert match is not None
        self.assertEqual(match.group(1), expected_digest)
        self.assertIn("Generated by docs/render_markdown.py", rendered)

    def test_active_plan_markdown_is_canonical_and_html_is_generated(self) -> None:
        paths = _active_plan_paths()
        if paths is None:
            return
        plan_md, plan_html = paths
        self.assertTrue(plan_md.is_file(), f"missing canonical plan: {plan_md}")
        self.assertTrue(plan_html.is_file(), f"missing generated plan: {plan_html}")
        source = plan_md.read_text(encoding="utf-8")
        rendered = plan_html.read_text(encoding="utf-8")
        expected = hashlib.sha256(source.encode("utf-8")).hexdigest()
        match = re.search(
            r'<meta name="source-sha256" content="([a-f0-9]{64})">',
            rendered,
        )
        self.assertIsNotNone(match)
        assert match is not None
        self.assertEqual(match.group(1), expected)
        self.assertIn("Generated by docs/render_markdown.py", rendered)
        self.assertIn("Canonical source:", rendered)

    def test_active_plan_has_required_compact_sections(self) -> None:
        paths = _active_plan_paths()
        if paths is None:
            return
        plan_md, _ = paths
        text = plan_md.read_text(encoding="utf-8")
        for heading in (
            "## Objective",
            "## Completion Usage",
            "## Scope Boundaries",
            "## Exit Criteria",
            "## Current Delivery",
            "### Current Frontier",
            "## Workflow History",
            "## Accepted Review Units",
            "## Open Risks And Unverified Assumptions",
            "## Milestone Decisions",
            "## Closeout",
        ):
            self.assertIn(heading, text, f"missing section {heading}")
        if "### Frontier Map" not in text:
            self.assertIn("### Next-Frontier Candidate", text)
            state = validate_plan_path(plan_md)
            expected_path = (
                (state.next_frontier.name,)
                if not state.next_frontier.is_empty
                else ()
            )
            self.assertEqual(state.frontier_map.path, expected_path)

    def test_legacy_active_plan_shape_uses_bounded_map_adoption(self) -> None:
        source = ready_plan_text()
        start = source.index("### Frontier Map")
        end = source.index("## Workflow History", start)
        legacy = source[:start] + source[end:]

        self.assertNotIn("### Frontier Map", legacy)
        state = validate_plan_text(legacy)
        self.assertEqual(state.status, "Active")
        self.assertEqual(state.frontier_map.path, (NEXT_FRONTIER,))
        self.assertEqual(
            tuple(node.name for node in state.frontier_map.nodes),
            (NEXT_FRONTIER,),
        )

    def test_completion_usage_starts_with_primary_demonstration(self) -> None:
        paths = _active_plan_paths()
        if paths is None:
            return
        plan_md, _ = paths
        table = parse_table(
            plan_md.read_text(encoding="utf-8"),
            "## Completion Usage",
        )
        self.assertEqual(
            table.header,
            ("Workflow", "Starting state", "Execution", "Success signal", "Criteria"),
        )
        self.assertTrue(table.rows, "Completion Usage must contain workflows")
        self.assertEqual(table.rows[0][0], "Primary demonstration")

    def test_active_plan_has_one_current_frontier_and_at_most_one_next(self) -> None:
        paths = _active_plan_paths()
        if paths is None:
            return
        plan_md, _ = paths
        state = validate_plan_path(plan_md)
        if state.current.is_empty:
            self.assertTrue(state.current.fields.get("reason"))
        else:
            self.assertTrue(state.current.fields["review question"])
        if not state.next_frontier.is_empty:
            self.assertTrue(state.next_frontier.fields["review question"])
        self.assertTrue(state.milestone_branch.startswith("milestone/"))

    def test_active_plan_exit_criteria_use_stable_ids(self) -> None:
        paths = _active_plan_paths()
        if paths is None:
            return
        plan_md, _ = paths
        state = validate_plan_path(plan_md)
        ids = [row[0] for row in state.criteria.rows]
        self.assertGreaterEqual(len(ids), 3)
        self.assertEqual(len(ids), len(set(ids)), "exit criteria IDs must be unique")

    def test_docs_guide_is_navigation_only_for_progress(self) -> None:
        guide = GUIDE.read_text(encoding="utf-8")
        self.assertIn("workflow.py status", guide)
        self.assertIn("completed.md", guide)
        self.assertNotIn("## Active Milestone", guide)
        self.assertNotIn("## Immediate Pre-Plan", guide)
        lowered = guide.lower()
        for banned in (
            "remaining for closeout",
            "package 5a",
            "package 5b",
            "required remediation order",
            "| current frontier |",
            "| status | active",
        ):
            self.assertNotIn(banned, lowered)

    def test_docs_guide_does_not_name_an_active_or_none_milestone(self) -> None:
        guide = GUIDE.read_text(encoding="utf-8")
        self.assertNotIn("**None.**", guide)
        self.assertIn("plan.md", guide)
        self.assertIsNone(STALE_MILESTONE_STATUS.search(guide))
        paths = _active_plan_paths()
        if paths is None:
            return
        plan_md, plan_html = paths
        self.assertTrue(plan_md.is_file())
        self.assertTrue(plan_html.is_file())

    def test_root_readme_does_not_claim_milestone_status(self) -> None:
        readme = ROOT_README.read_text(encoding="utf-8")
        self.assertIsNone(STALE_MILESTONE_STATUS.search(readme))
        self.assertNotIn("## Active Milestone", readme)
        self.assertIn("docs/README.md", readme)
        self.assertIn("completed.md", readme)

    def test_review_unit_pr_template_has_required_headings(self) -> None:
        self.assertTrue(PR_TEMPLATE.is_file())
        text = PR_TEMPLATE.read_text(encoding="utf-8")
        for heading in (
            "## Milestone Context",
            "## Accepted Proposal",
            "## Review Kind",
            "## Review Question",
            "## Repair Cycle Ledger",
            "## Validation",
        ):
            self.assertIn(heading, text)
        self.assertNotIn("## Repair Escalation", text)
        self.assertNotIn("## Repair Continuation Audit", text)
        self.assertIn("matching the canonical milestone plan", text)

    def test_proposal_pr_template_forbids_implementation(self) -> None:
        self.assertTrue(PROPOSAL_PR_TEMPLATE.is_file())
        text = PROPOSAL_PR_TEMPLATE.read_text(encoding="utf-8")
        self.assertIn("## Independence Check", text)
        self.assertIn("## Review Kind", text)
        self.assertIn("## Operator Want", text)
        self.assertIn("## Evidence rendering", text)
        self.assertIn("work-order artifact", text)
        self.assertIn("- Evidence directory (if yes):", text)
        self.assertIn("repository-relative directory path", text)
        self.assertIn("Trust And Authority Model", text)
        self.assertIn("Evidence Topology And Capture Strategy", text)
        self.assertIn("No product or runtime implementation changed", text)
        self.assertIn("Proposal artifact", text)
        self.assertIn("## Contract Review Receipt", text)
        self.assertIn("current repository push authority", text)
        self.assertIn("unedited COMMENT review", text)
        self.assertIn("## Repair Cycle Ledger", text)
        self.assertNotIn("## Repair Escalation", text)
        self.assertNotIn("## Repair Continuation Audit", text)

    def test_universal_claim_contractability_is_visible_in_author_guidance(
        self,
    ) -> None:
        contract = CONTRACT_SOURCE.read_text(encoding="utf-8")
        guidance = PROPOSAL_GUIDANCE.read_text(encoding="utf-8")
        for phrase in (
            "Trust And Authority Model",
            "Evidence Topology And Capture Strategy",
        ):
            self.assertIn(phrase, contract)
            self.assertIn(phrase, guidance)
        normalized_contract = " ".join(contract.split())
        self.assertIn(
            "consistency, provenance, and authenticity",
            normalized_contract,
        )
        self.assertIn("canonical capture is ready", guidance)

    def test_proposal_amendment_template_preserves_accepted_contract(self) -> None:
        self.assertTrue(PROPOSAL_AMENDMENT_PR_TEMPLATE.is_file())
        text = PROPOSAL_AMENDMENT_PR_TEMPLATE.read_text(encoding="utf-8")
        self.assertIn("## Review Kind", text)
        self.assertIn("## Evidence Requiring Amendment", text)
        self.assertIn("## Operator Want", text)
        self.assertIn("Trust And Authority Model", text)
        self.assertIn("Evidence Topology And Capture Strategy", text)
        self.assertIn("No accepted proposal or prior amendment was modified", text)
        self.assertIn("No product or runtime implementation changed", text)
        self.assertIn("## Contract Review Receipt", text)
        self.assertIn("current repository push authority", text)
        self.assertIn("## Repair Cycle Ledger", text)
        self.assertNotIn("## Repair Escalation", text)
        self.assertNotIn("## Repair Continuation Audit", text)

    def test_implementation_adjunct_template_records_human_compatibility(self) -> None:
        self.assertTrue(IMPLEMENTATION_ADJUNCT_PR_TEMPLATE.is_file())
        text = IMPLEMENTATION_ADJUNCT_PR_TEMPLATE.read_text(encoding="utf-8")
        for heading in (
            "## Parent Implementation",
            "## Operator Request",
            "## HITL Authorization",
            "## Review Question",
            "## Compatibility",
            "## Evidence Impact",
            "## Repair Cycle Ledger",
            "## Validation",
        ):
            self.assertIn(heading, text)
        self.assertNotIn("## Repair Escalation", text)
        self.assertIn("Requested disposition: `implement-now`", text)
        self.assertIn("parent contract remains true without this adjunct", text)
        self.assertIn("Base implementation branch", text)

    def test_cumulative_milestone_pr_template_targets_main_topology(self) -> None:
        self.assertTrue(MILESTONE_PR_TEMPLATE.is_file())
        text = MILESTONE_PR_TEMPLATE.read_text(encoding="utf-8")
        self.assertIn("Targets: `main`", text)
        self.assertIn("milestone branch", text.lower())
        self.assertIn("## Accepted Review Units", text)
        self.assertIn("## Repair Cycle Ledger", text)
        self.assertNotIn("## Repair Escalation", text)
        self.assertNotIn("## Repair Continuation Audit", text)

    def test_repair_template_carries_cycle_and_escalation_receipts(self) -> None:
        self.assertTrue(REPAIR_PR_TEMPLATE.is_file())
        text = REPAIR_PR_TEMPLATE.read_text(encoding="utf-8")
        self.assertIn("## Review Repair Summary", CONTRACT_SOURCE.read_text(encoding="utf-8"))
        self.assertIn("## Repair Cycle Ledger", text)
        self.assertNotIn("## Repair Escalation", text)
        self.assertNotIn("## Repair Continuation Audit", text)

    def test_review_unit_template_repair_receipt_defaults_are_valid(self) -> None:
        for path in (
            PR_TEMPLATE,
            PROPOSAL_PR_TEMPLATE,
            PROPOSAL_AMENDMENT_PR_TEMPLATE,
            IMPLEMENTATION_ADJUNCT_PR_TEMPLATE,
            MILESTONE_PR_TEMPLATE,
            REPAIR_PR_TEMPLATE,
        ):
            with self.subTest(path=path):
                self.assertEqual(
                    validate_repair_cycle_governance_body(
                        path.read_text(encoding="utf-8")
                    ),
                    0,
                )

    def test_pr_body_edits_revalidate_repair_receipts(self) -> None:
        text = TEST_WORKFLOW.read_text(encoding="utf-8")
        self.assertRegex(text, r"types:.*\bedited\b")
        self.assertIn("pull-requests: read", text)
        self.assertIn("GH_TOKEN:", text)

    def test_pr_body_edits_rerun_review_kind_validation(self) -> None:
        text = TEST_WORKFLOW.read_text(encoding="utf-8")
        self.assertRegex(
            text,
            r"pull_request:\s*\n\s+types: \[[^\]]*edited[^\]]*\]",
        )

    def test_review_events_rerun_receipt_validation(self) -> None:
        text = TEST_WORKFLOW.read_text(encoding="utf-8")
        self.assertRegex(
            text,
            r"pull_request_review:\s*\n\s+types: \[[^\]]*submitted[^\]]*\]",
        )
        self.assertIn("dismissed", text)
        self.assertIn("github.event.pull_request.head.ref", text)
        self.assertIn("github.event_name == 'pull_request_review'", text)

    def test_contract_defines_work_unit_terms_and_branch_model(self) -> None:
        text = CONTRACT_SOURCE.read_text(encoding="utf-8")
        for term in (
            "### Milestone",
            "### Frontier",
            "### Review Unit",
            "### Task",
            "### Evidence Unit",
            "### Repair Cycle",
            "### Closeout",
            "milestone/<number>-<slug>",
            "m<number>/<frontier>-proposal",
            "m<number>/<frontier>--adjunct-<slug>",
        ):
            self.assertIn(term, text)
        self.assertIn("targets the milestone branch", text.lower())

    def test_contract_routes_human_discovery_without_reopening_parent(self) -> None:
        text = CONTRACT_SOURCE.read_text(encoding="utf-8")
        normalized = " ".join(text.split())
        self.assertIn("### Human Discovery During Implementation", text)
        self.assertIn("parent contract remains true", text.lower())
        self.assertIn("implement-now", text)
        self.assertIn("creates no plan transition", normalized)
        self.assertIn("review the integrated parent in totality", normalized)

    def test_contract_discourages_multiple_independent_review_questions(self) -> None:
        text = CONTRACT_SOURCE.read_text(encoding="utf-8")
        self.assertIn("Singular Review Question Rule", text)
        self.assertIn('requires “and”', text)

    def test_contract_has_evidence_based_repair_continuation_gate(self) -> None:
        text = CONTRACT_SOURCE.read_text(encoding="utf-8")
        normalized = " ".join(text.split())
        self.assertIn("There is no cycle count that pauses review", text)
        self.assertIn("Closed implementation review", text)
        self.assertIn("Late implementer collapse", text)
        self.assertIn("Derived evidence rendering", text)
        self.assertIn("one stable evidence directory", normalized)
        self.assertIn("repository-relative path", normalized)
        self.assertNotIn("shared directory is acceptable", text.lower())
        self.assertIn("Do not invent", text)
        self.assertIn("operator", text.lower())
        self.assertIn("leftover shapes", text)
        self.assertIn("inside the accepted owner", text)
        self.assertIn("different named owner", text)
        self.assertNotIn("Moving internals or touching more files", text)
        self.assertIn("Outcome: `accepted`", text)
        self.assertIn("documentary", text.lower())
        self.assertIn("a new PR number is not reviewability evidence", normalized)
        self.assertIn("currently fails closed", normalized)
        self.assertIn("becomes authoritative only after", normalized)
        self.assertIn("already open at merge do not migrate automatically", normalized)
        self.assertIn("introducing PR remains governed by its base contract", normalized)
        self.assertIn("Repair Cycle Ledger", text)
        self.assertNotIn("Repair Escalation", text)

    def test_contract_assigns_frontier_handoff_to_executable_workflow(self) -> None:
        text = CONTRACT_SOURCE.read_text(encoding="utf-8")
        normalized = " ".join(text.split())
        self.assertIn("Frontier handoff:", text)
        self.assertIn("docs/milestones/workflow.py complete-implementation", text)
        self.assertIn("handoff --receipt <path>", text)
        self.assertIn("docs/milestones/workflow.py accept-proposal", text)
        self.assertIn(
            "docs/milestones/workflow.py accept-proposal-amendment",
            text,
        )
        self.assertIn("git switch -c", text)
        self.assertIn("optional helpers", text)
        self.assertIn("merge commit that is not already an ancestor", normalized)
        self.assertIn("sets current to idle", text)

    def test_contract_requires_next_frontier_minimal_acceptance_contract(self) -> None:
        text = CONTRACT_SOURCE.read_text(encoding="utf-8")
        normalized = " ".join(text.split())
        self.assertIn("pre-implementation acceptance contract", text)
        self.assertIn("select current from the artifact", normalized)
        self.assertIn("enforcement or acceptance owner", text)
        self.assertIn("A name plus a vague “likely question” alone is not a candidate", text)
        self.assertIn("empty remaining path", text)
        self.assertIn("### Frontier Map", text)
        self.assertIn("linked-list", text)
        self.assertIn("cannot delete a contracted node", text)

    def test_contract_requires_one_primary_completion_demonstration(self) -> None:
        text = CONTRACT_SOURCE.read_text(encoding="utf-8")
        self.assertIn("The first body row must be `Primary demonstration`", text)
        self.assertIn("leave schemas, lifecycle matrices, edge cases", text)

    def test_active_plan_next_frontier_records_minimal_contract_fields(self) -> None:
        paths = _active_plan_paths()
        if paths is None:
            return
        plan_md, _ = paths
        state = validate_plan_path(plan_md)
        frontiers = []
        if not state.current.is_empty:
            frontiers.append(state.current)
        if not state.next_frontier.is_empty:
            frontiers.append(state.next_frontier)
        for frontier in frontiers:
            for field in (
                "proposal branch",
                "implementation branch",
                "proposal path",
                "review kind",
                "review question",
                "acceptance owner",
                "exit criteria affected",
                "prerequisite",
                "non-goals",
            ):
                self.assertTrue(frontier.fields[field], f"missing frontier field {field}")
        from docs.milestones.workflow import WORKFLOW_STATES

        if state.current.is_empty:
            self.assertTrue(state.current.fields.get("reason"))
        else:
            self.assertIn(
                state.current.fields["workflow state"],
                WORKFLOW_STATES,
            )

    def test_repository_accepts_active_idle_current(self) -> None:
        state = validate_plan_text(
            apply_handoff(implementation_review_plan_text(), handoff_receipt())
        )
        self.assertEqual(state.status, "Active")
        self.assertTrue(state.current.is_empty)
        self.assertEqual(state.next_frontier.name, NEXT_FRONTIER)
        self.assertEqual(state.frontier_map.path, (NEXT_FRONTIER,))


if __name__ == "__main__":
    unittest.main(verbosity=2)
