import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { marked } from "marked";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDirectory, "..");
const docsDirectory = path.join(projectRoot, "docs");
const milestoneDirectory = path.join(docsDirectory, "milestones");
const contractSourcePath = path.join(milestoneDirectory, "README.md");
const contractOutputPath = path.join(milestoneDirectory, "planning-contract.html");
const docsGuidePath = path.join(docsDirectory, "README.md");
const validWorkStatuses = new Set(["pending", "active", "blocked", "done"]);
const requiredPlanSections = [
  "High-Level Objective",
  "Completion Usage",
  "Baseline",
  "Current Delivery Horizon",
  "Work Plan",
  "Scope Boundaries",
  "Risks And Controls",
  "Exit Criteria",
  "Decision Log",
];

function toPosixRelative(targetPath) {
  return path.relative(projectRoot, targetPath).split(path.sep).join("/");
}

function contractDigest(source) {
  return crypto.createHash("sha256").update(source, "utf8").digest("hex");
}

function renderContract(source) {
  const digest = contractDigest(source);
  const content = marked.parse(source, { gfm: true });
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="source-sha256" content="${digest}">
  <base target="_blank">
  <title>Milestone Planning Contract</title>
  <style>
    :root { --ink: #17211f; --muted: #596762; --line: #c9d5ce; --bg: #f5f7f4; --panel: #fff; --teal: #26778a; --neutral: #edf1ee; }
    * { box-sizing: border-box; }
    body { margin: 0; background: var(--bg); color: var(--ink); font-family: Inter, ui-sans-serif, system-ui, sans-serif; line-height: 1.55; }
    main { width: min(900px, calc(100% - 30px)); margin: 0 auto; padding: 24px 0 48px; }
    .source { margin-bottom: 20px; padding: 10px 12px; border: 1px solid var(--line); border-radius: 6px; background: var(--panel); color: var(--muted); font-size: 13px; }
    h1, h2, h3 { letter-spacing: 0; line-height: 1.2; }
    h1 { margin: 0 0 20px; font-size: 32px; }
    h2 { margin: 28px 0 10px; padding-bottom: 7px; border-bottom: 1px solid var(--line); font-size: 21px; }
    h3 { margin: 20px 0 8px; font-size: 16px; }
    p, li { color: var(--muted); }
    p { margin: 9px 0; }
    li { margin: 5px 0; }
    a { color: var(--teal); }
    code { padding: 2px 5px; border-radius: 4px; background: var(--neutral); color: #1e3932; }
    pre { overflow-x: auto; padding: 13px; border-radius: 6px; background: var(--ink); color: #e6f1eb; }
    pre code { padding: 0; background: transparent; color: inherit; }
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 9px; border-bottom: 1px solid var(--line); text-align: left; vertical-align: top; }
    th { background: var(--neutral); }
  </style>
</head>
<body>
  <!-- Generated by scripts/milestone-docs.mjs. Do not edit directly. -->
  <main>
    <div class="source">Canonical source: <a href="README.md">README.md</a></div>
    ${content}
  </main>
</body>
</html>
`;
}

function activePlanPath() {
  const guide = fs.readFileSync(docsGuidePath, "utf8");
  const match = guide.match(
    /Milestone \d+,\s*\[[^\]]+\]\((milestones\/[^)]+\/plan\.html)\),\s*is active\./u,
  );
  if (!match) {
    throw new Error("docs/README.md must identify one active milestone plan.");
  }
  return path.join(docsDirectory, ...match[1].split("/"));
}

function validateSectionOrder(plan, planPath) {
  let previousIndex = -1;
  requiredPlanSections.forEach((section) => {
    const marker = `<h2>${section}</h2>`;
    const sectionIndex = plan.indexOf(marker);
    if (sectionIndex < 0) {
      throw new Error(`${toPosixRelative(planPath)} is missing ${marker}.`);
    }
    if (sectionIndex <= previousIndex) {
      throw new Error(`${toPosixRelative(planPath)} has milestone sections out of order.`);
    }
    previousIndex = sectionIndex;
  });
}

function validateWorkProgress(plan, planPath) {
  const statuses = [...plan.matchAll(/<details class="work-item" data-status="([^"]+)"/gu)]
    .map((match) => match[1]);
  if (statuses.length === 0) {
    throw new Error(`${toPosixRelative(planPath)} must define trackable work items.`);
  }
  const invalidStatus = statuses.find((status) => !validWorkStatuses.has(status));
  if (invalidStatus) {
    throw new Error(`${toPosixRelative(planPath)} uses invalid work status: ${invalidStatus}.`);
  }

  const progress = plan.match(/Milestone work packages completed: (\d+) of (\d+)/u);
  if (!progress) {
    throw new Error(`${toPosixRelative(planPath)} must expose aggregate milestone progress.`);
  }
  const doneCount = statuses.filter((status) => status === "done").length;
  const reportedDone = Number(progress[1]);
  const reportedTotal = Number(progress[2]);
  if (reportedDone !== doneCount || reportedTotal !== statuses.length) {
    throw new Error(
      `${toPosixRelative(planPath)} reports ${reportedDone}/${reportedTotal} progress but contains ${doneCount}/${statuses.length} completed work items.`,
    );
  }
}

function validateActivePlan() {
  const planPath = activePlanPath();
  if (!fs.existsSync(planPath)) {
    throw new Error(`Active milestone plan does not exist: ${toPosixRelative(planPath)}.`);
  }
  const plan = fs.readFileSync(planPath, "utf8");
  validateSectionOrder(plan, planPath);
  validateWorkProgress(plan, planPath);

  const requiredMarkers = [
    "data-completion-usage",
    "<strong>Starting state:</strong>",
    "<strong>Proposed execution:</strong>",
    "<strong>Success signal:</strong>",
    "data-shared-planning-contract",
    "data-milestone-contract",
    'src="../planning-contract.html"',
  ];
  requiredMarkers.forEach((marker) => {
    if (!plan.includes(marker)) {
      throw new Error(`${toPosixRelative(planPath)} is missing required marker: ${marker}.`);
    }
  });
  return planPath;
}

function run({ check }) {
  const source = fs.readFileSync(contractSourcePath, "utf8");
  const rendered = renderContract(source);
  if (check) {
    const current = fs.existsSync(contractOutputPath)
      ? fs.readFileSync(contractOutputPath, "utf8")
      : null;
    if (current !== rendered) {
      throw new Error(
        "docs/milestones/planning-contract.html is stale; run `npm run docs:milestones`.",
      );
    }
  } else {
    fs.mkdirSync(path.dirname(contractOutputPath), { recursive: true });
    fs.writeFileSync(contractOutputPath, rendered, "utf8");
    console.log(`Rendered ${toPosixRelative(contractOutputPath)}`);
  }

  const planPath = validateActivePlan();
  console.log(`Validated ${toPosixRelative(planPath)}`);
}

try {
  run({ check: process.argv.includes("--check") });
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
}
