#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import html
import os
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from docs.milestones.workflow import (
    PlanContractError,
    render_plan_text,
    validate_plan_path,
)

try:
    import markdown
except ImportError as exc:  # pragma: no cover
    raise SystemExit(
        "Markdown rendering requires `python3 -m pip install -r docs/requirements.txt`."
    ) from exc

MILESTONES = ROOT / "docs" / "milestones"


@dataclass(frozen=True)
class RenderedMarkdown:
    source: Path
    target: Path
    title: str


def discover_documents() -> tuple[RenderedMarkdown, ...]:
    documents: list[RenderedMarkdown] = [
        RenderedMarkdown(
            source=MILESTONES / "README.md",
            target=MILESTONES / "planning-contract.html",
            title="Milestone Planning And Delivery Contract",
        )
    ]
    for plan_md in sorted(MILESTONES.glob("*/plan.md")):
        slug = plan_md.parent.name
        documents.append(
            RenderedMarkdown(
                source=plan_md,
                target=plan_md.with_suffix(".html"),
                title=f"Milestone plan — {slug}",
            )
        )
    return tuple(documents)


def source_digest(source_text: str) -> str:
    return hashlib.sha256(source_text.encode("utf-8")).hexdigest()


def render_document(document: RenderedMarkdown) -> str:
    source_text = document.source.read_text(encoding="utf-8")
    digest = source_digest(source_text)
    source_href = Path(os.path.relpath(document.source, document.target.parent)).as_posix()
    rendered_text = (
        render_plan_text(source_text)
        if document.source.name == "plan.md"
        else source_text
    )
    body = markdown.markdown(
        rendered_text,
        extensions=("extra", "sane_lists", "tables"),
        output_format="html5",
    )
    title = html.escape(document.title)
    source_href = html.escape(source_href, quote=True)
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="source-sha256" content="{digest}">
  <base target="_blank">
  <title>{title}</title>
  <style>
    :root {{
      --ink: #17211f;
      --muted: #596762;
      --line: #c9d5ce;
      --bg: #f5f7f4;
      --panel: #ffffff;
      --teal: #26778a;
      --neutral: #edf1ee;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      background: var(--bg);
      color: var(--ink);
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      line-height: 1.55;
    }}
    main {{ width: min(960px, calc(100% - 30px)); margin: 0 auto; padding: 24px 0 48px; }}
    .source {{
      margin-bottom: 20px;
      padding: 10px 12px;
      border: 1px solid var(--line);
      border-radius: 6px;
      background: var(--panel);
      color: var(--muted);
      font-size: 13px;
    }}
    h1, h2, h3 {{ letter-spacing: 0; line-height: 1.2; color: var(--ink); }}
    h1 {{ margin: 0 0 20px; font-size: 32px; }}
    h2 {{ margin: 28px 0 10px; padding-bottom: 7px; border-bottom: 1px solid var(--line); font-size: 21px; }}
    h3 {{ margin: 20px 0 8px; font-size: 16px; }}
    p, li {{ color: var(--muted); }}
    p {{ margin: 9px 0; }}
    li {{ margin: 5px 0; }}
    a {{ color: var(--teal); }}
    code {{ padding: 2px 5px; border-radius: 4px; background: var(--neutral); color: #1e3932; }}
    pre {{ overflow-x: auto; padding: 13px; border-radius: 6px; background: var(--ink); color: #e6f1eb; }}
    pre code {{ padding: 0; background: transparent; color: inherit; }}
    table {{ width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 14px; }}
    th, td {{ padding: 9px; border: 1px solid var(--line); text-align: left; vertical-align: top; }}
    th {{ background: var(--neutral); color: var(--ink); }}
    td {{ color: var(--muted); background: var(--panel); }}
    blockquote {{
      margin: 12px 0;
      padding: 8px 14px;
      border-left: 4px solid var(--teal);
      background: var(--neutral);
      color: var(--muted);
    }}
  </style>
</head>
<body>
  <!-- Generated by docs/render_markdown.py. Do not edit directly. -->
  <main>
    <div class="source">Canonical source: <a href="{source_href}">{source_href}</a></div>
    {body}
  </main>
</body>
</html>
"""


def run(*, check: bool) -> int:
    documents = discover_documents()
    stale: list[Path] = []
    for document in documents:
        if document.source.name == "plan.md":
            try:
                validate_plan_path(document.source)
            except PlanContractError as exc:
                print(
                    f"Invalid milestone plan: {document.source.relative_to(ROOT)}: {exc}"
                )
                return 1
        rendered = render_document(document)
        if check:
            if not document.target.exists() or document.target.read_text(encoding="utf-8") != rendered:
                stale.append(document.target)
            continue
        document.target.parent.mkdir(parents=True, exist_ok=True)
        document.target.write_text(rendered, encoding="utf-8")
        print(f"Rendered {document.target.relative_to(ROOT)}")

    if stale:
        for target in stale:
            print(f"Stale rendered Markdown: {target.relative_to(ROOT)}")
        print("Run `python3 docs/render_markdown.py` to refresh generated documentation.")
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Render configured repository Markdown documents as standalone HTML.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when a generated HTML document differs from its Markdown source.",
    )
    args = parser.parse_args()
    return run(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
